sudo: required

services:
- docker

env:
  global:
  - DOCKER_USERNAME=guillaumejacquenot
  - secure: "iPY7cvdwF7wxJ88v8OSBmdSkoMdXGTdVeAngjRVBrvui5EfJAXl5NgW5YEVdMuDRbddrh2J7d+Zb3xPXm258F2AymPIHXgIGxBEjJbA+UEYOfnBxsMmf2TrVpCPpN7j12aMgdvfNF6LeLpfMspRHcIDhG+ROuz3h1TxfBcPYaU7jopByZfskc5fRy+0ymbGa7QQMSHDw6LZQQ6QWLelOWXa3odZLf0axmhQ5ahLtB3zwABo1AeoXUUPZOMXCYcpE6lxOG9yySJedzkQFy5JqKNl6wMGtrCtSKrgZGsEL9zExE1HPwPIR+Wvl5lzQ2l2V+rWVq3hfcgdbBjedZZSCtEvIdRNKjFaNzujJmLjoBlR1HhXgmPcyfeTK7ErFzjp4mENgn65JgdX6nY7S5XdeDlGRXHRd6w17Yeqh2sQNw7M4TZ25faNChxufEwxO3icjOOg8DbE8ZlWTQFQ3gaogtw2GXrIMTQEX+ymSjdJExuqP5y5vG7kWJ7h2iHNzSEfP5uHlIj48Hp9VoKnXgxyr0hOpRP9rvCCE6qSuqhFVyBByH7/ZVF9hg/Q/Q+Wmsx9rT2SNIe4WV5EZ198sSG6ggUqh6w+IywS6kfzcH4Di5TT8VNqz8q97bCACW5nmxYSGtCfEF3cK3bn4ZQ9s8P1tWCbPrKWVbPLT5ZD/q2ON/qU="

before_install:
- echo "Before install"

before_script:
- docker pull sirehna/base-image-debian9-gcc820-xdyn || true

script:
- docker build --pull --cache-from sirehna/base-image-debian9-gcc820-xdyn --tag sirehna/base-image-debian9-gcc820-xdyn .

after_script:
- docker images

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker login -u $DOCKER_USERNAME -p
  $DOCKER_PASSWORD ; docker push sirehna/base-image-debian9-gcc820-xdyn ; fi

notifications:
  email: true

